from __future__ import annotations

import sqlite3

import pytest

from app import auth, config, crypto
from app.plugins.base import registry
from app.scheduler import scheduler
from app.storage import db
from app.storage.cache import cache


@pytest.fixture(autouse=True)
def _reset_shared_state():
    """The plugin registry, TTL cache, and PIN-login lockout tracker are
    process-wide singletons; tests must not leak registrations or cached
    values into each other."""
    registry._plugins.clear()
    cache._store.clear()
    auth._failed_attempts.clear()
    scheduler.remove_all_jobs()
    yield
    registry._plugins.clear()
    cache._store.clear()
    auth._failed_attempts.clear()
    scheduler.remove_all_jobs()


@pytest.fixture(autouse=True)
def _reset_ambient_settings(monkeypatch):
    """`app.config.settings` is a process-wide singleton loaded once from
    `.env` at import time. A developer's local `.env` commonly carries real
    provider API keys for manual testing, so tests must not see them —
    otherwise results (e.g. `has_<key>` flags) depend on whichever secrets
    happen to be configured on the machine running the suite."""
    for key in config.APP_SETTINGS_KEYS:
        monkeypatch.setattr(config.settings, key, config.Settings.model_fields[key].default, raising=False)


@pytest.fixture
def tmp_db(tmp_path, monkeypatch):
    """Point app.storage.db at an isolated sqlite file for this test.

    Also isolates the secret-encryption key (app.crypto) to the same tmp
    dir — otherwise every test process would share (and create on disk) the
    real backend/secret.key file, and a key generated by one test run would
    silently make ciphertext from a previous run undecryptable.
    """
    db_path = tmp_path / "test.db"
    monkeypatch.setattr(db, "DB_PATH", db_path)
    monkeypatch.setattr(crypto, "SECRET_KEY_PATH", tmp_path / "secret.key")
    crypto.reset_key_cache()
    db.init_db()
    return db_path


@pytest.fixture
def tmp_db_pre_token_hashing(tmp_path, monkeypatch):
    """Like `tmp_db`, but stops one migration short of migration 019 (the
    one that rehashes `devices.id`/`sessions.id` to match
    `app.auth._hash_token`), so a test can seed rows the old, pre-v0.15.0
    way — the raw bearer token as the primary key, as every row was before
    that release added hashing — and then call `db.init_db()` itself to
    exercise the migration.
    """
    db_path = tmp_path / "test.db"
    monkeypatch.setattr(db, "DB_PATH", db_path)
    monkeypatch.setattr(crypto, "SECRET_KEY_PATH", tmp_path / "secret.key")
    crypto.reset_key_cache()
    conn = sqlite3.connect(db_path)
    try:
        conn.executescript(db._SCHEMA)
        conn.execute(f"PRAGMA user_version = {len(db._MIGRATIONS) - 1}")
        conn.commit()
    finally:
        conn.close()
    return db_path
