"""Best-effort, on-disk-cached closed captions and scrub-bar thumbnails for
completed HDHomeRun DVR recordings.

Both are generated by running `ffmpeg` once against the whole recording file
and never regenerated after that — a completed recording is static, so the
first successful (or failed) attempt is final for that `recording_id`. Only
ever call these against a completed recording: an actively-growing DVR file
would produce an incomplete/wrong result.

Everything here degrades to `None` on any failure (missing ffmpeg, no
captions present, an unreachable URL) rather than raising — captions and
thumbnails are enhancements, not something a recording's playback should
ever fail over.
"""

from __future__ import annotations

import asyncio
import contextlib
import math
from pathlib import Path

from app.config import HDHOMERUN_MEDIA_CACHE_DIR

# Caption extraction decodes the whole file (no way to sample a prefix like
# the ffprobe detection pass does, since we don't know where in the
# recording captions will actually appear), at roughly 2 minutes of ffmpeg
# time per hour of content observed against real ATSC recordings - so this
# needs enough headroom for a multi-hour recording, not just a half-hour one.
_GENERATE_TIMEOUT_SECONDS = 600
_SPRITE_COLUMNS = 10
_SPRITE_ROWS = 10
_SPRITE_TILE_WIDTH = 160
_SPRITE_TILE_HEIGHT = 90
_MIN_SPRITE_INTERVAL_SECONDS = 2.0


def _cache_dir() -> Path:
    HDHOMERUN_MEDIA_CACHE_DIR.mkdir(parents=True, exist_ok=True)
    return HDHOMERUN_MEDIA_CACHE_DIR


def _escape_movie_filter_url(url: str) -> str:
    """Escape a URL for use inside a quoted lavfi filtergraph argument.

    Single-quoting protects filtergraph-level syntax (commas, brackets,
    semicolons) but NOT colons - the `movie` filter's own per-filter option
    parser splits on the first unescaped `:` after the filename to find
    `:options`, even inside single quotes (e.g. an unescaped
    `http://host:port/...` gets truncated at the port's colon, and
    everything after it gets silently mis-parsed as filter options, so
    ffmpeg exits immediately with no video opened at all). So colons need
    their own backslash escape in addition to backslash/single-quote.
    """
    return url.replace("\\", "\\\\").replace("'", "\\'").replace(":", "\\:")


async def _run_ffmpeg(argv: list[str]) -> bool:
    try:
        process = await asyncio.create_subprocess_exec(
            *argv,
            stdin=asyncio.subprocess.DEVNULL,
            stdout=asyncio.subprocess.DEVNULL,
            stderr=asyncio.subprocess.PIPE,
        )
    except OSError:
        return False

    try:
        await asyncio.wait_for(process.communicate(), timeout=_GENERATE_TIMEOUT_SECONDS)
    except TimeoutError:
        process.kill()
        with contextlib.suppress(Exception):
            await process.wait()
        return False

    return process.returncode == 0


async def generate_captions_vtt(url: str, recording_id: str) -> Path | None:
    """The cached WebVTT captions file for `recording_id`, generating it first if needed.

    Returns None if extraction fails or the recording has no embedded
    CEA-608/708 captions - both look identical from here (ffmpeg exits 0
    either way when the source has no caption data, just with an
    effectively empty subtitle stream), so a missing/empty result is
    treated as "no captions" rather than surfaced as an error.
    """
    cache_path = _cache_dir() / f"{recording_id}.vtt"
    if cache_path.exists():
        return cache_path if cache_path.stat().st_size > 0 else None

    tmp_path = cache_path.with_suffix(".vtt.tmp")
    escaped_url = _escape_movie_filter_url(url)
    argv = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-f",
        "lavfi",
        "-i",
        f"movie='{escaped_url}'[out+subcc]",
        "-map",
        "0:s:0",
        "-f",
        "webvtt",
        "-y",
        str(tmp_path),
    ]
    ok = await _run_ffmpeg(argv)
    if not ok:
        # A non-zero exit / timeout / missing binary isn't a confirmed
        # "no captions" result - it could be a slow/unreachable DVR, a
        # too-short timeout, or a transient ffmpeg crash - so don't cache
        # it as permanent failure. Only a *successful* ffmpeg run with an
        # empty result (below) means the source genuinely has no captions.
        with contextlib.suppress(FileNotFoundError):
            tmp_path.unlink()
        return None

    if not tmp_path.exists():
        cache_path.touch()
        return None

    tmp_path.replace(cache_path)
    return cache_path if cache_path.stat().st_size > 0 else None


def _sprite_paths(recording_id: str) -> tuple[Path, Path]:
    return _cache_dir() / f"{recording_id}.jpg", _cache_dir() / f"{recording_id}.thumbs.vtt"


def _format_timestamp(seconds: float) -> str:
    hours, remainder = divmod(max(0.0, seconds), 3600)
    minutes, secs = divmod(remainder, 60)
    return f"{int(hours):02d}:{int(minutes):02d}:{secs:06.3f}"


def _build_sprite_vtt(jpg_filename: str, interval_seconds: float, tile_count: int, grid_columns: int) -> str:
    lines = ["WEBVTT", ""]
    for index in range(tile_count):
        start = index * interval_seconds
        end = (index + 1) * interval_seconds
        col = index % grid_columns
        row = index // grid_columns
        x = col * _SPRITE_TILE_WIDTH
        y = row * _SPRITE_TILE_HEIGHT
        lines.append(f"{_format_timestamp(start)} --> {_format_timestamp(end)}")
        lines.append(f"{jpg_filename}#xywh={x},{y},{_SPRITE_TILE_WIDTH},{_SPRITE_TILE_HEIGHT}")
        lines.append("")
    return "\n".join(lines)


async def generate_thumbnail_sprite(url: str, recording_id: str, duration_seconds: float) -> tuple[Path, Path] | None:
    """The cached (sprite JPEG, cue VTT) pair for `recording_id`, generating first if needed.

    A single `_SPRITE_COLUMNS`x`_SPRITE_ROWS` grid is spread evenly across
    the whole recording (interval adapts to duration) rather than sampling
    at a fixed interval, so a long recording doesn't lose thumbnail
    coverage past the first few minutes.
    """
    jpg_path, vtt_path = _sprite_paths(recording_id)
    if jpg_path.exists() and vtt_path.exists():
        return jpg_path, vtt_path

    if duration_seconds <= 0:
        return None

    tile_count = _SPRITE_COLUMNS * _SPRITE_ROWS
    interval_seconds = max(_MIN_SPRITE_INTERVAL_SECONDS, duration_seconds / tile_count)
    actual_tile_count = min(tile_count, max(1, math.ceil(duration_seconds / interval_seconds)))

    # The tile filter's WxH area is sized for the worst case (a long
    # recording sampled down to the full grid). A short recording samples
    # far fewer frames than that, and the filter only ever emits an output
    # frame once it's buffered a full W*H input frames — so a fixed
    # _SPRITE_COLUMNS x _SPRITE_ROWS area would silently produce nothing for
    # anything shorter than that. Size the grid to what's actually sampled,
    # and cap nb_frames to the same count so the filter flushes as soon as
    # those frames arrive instead of waiting for a full grid.
    grid_columns = min(_SPRITE_COLUMNS, actual_tile_count)
    grid_rows = math.ceil(actual_tile_count / grid_columns)

    tmp_jpg = jpg_path.with_suffix(".jpg.tmp")
    argv = [
        "ffmpeg",
        "-hide_banner",
        "-loglevel",
        "error",
        "-i",
        url,
        "-vf",
        (
            f"fps=1/{interval_seconds},scale={_SPRITE_TILE_WIDTH}:{_SPRITE_TILE_HEIGHT},"
            f"tile={grid_columns}x{grid_rows}:nb_frames={actual_tile_count}"
        ),
        "-frames:v",
        "1",
        "-q:v",
        "4",
        "-y",
        str(tmp_jpg),
    ]
    ok = await _run_ffmpeg(argv)
    if not ok or not tmp_jpg.exists():
        with contextlib.suppress(FileNotFoundError):
            tmp_jpg.unlink()
        return None

    tmp_jpg.replace(jpg_path)
    vtt_path.write_text(_build_sprite_vtt(jpg_path.name, interval_seconds, actual_tile_count, grid_columns))
    return jpg_path, vtt_path
