"""ICAO aircraft type designator -> aircraft manufacturer & model lookup.

ADS-B feeds report aircraft types as standard 4-character ICAO designators
(e.g., "B738", "A321", "C172", "E75L", "B38M"). This module maps these codes
to human-readable names and manufacturer information for display in the UI.
"""

from __future__ import annotations

# Map of ICAO aircraft type designator to full name / model details.
AIRCRAFT_BY_ICAO: dict[str, dict[str, str]] = {
    # Boeing Commercial
    "B737": {"name": "Boeing 737-700", "manufacturer": "Boeing", "model": "737-700"},
    "B738": {"name": "Boeing 737-800", "manufacturer": "Boeing", "model": "737-800"},
    "B739": {"name": "Boeing 737-900", "manufacturer": "Boeing", "model": "737-900"},
    "B37M": {"name": "Boeing 737 MAX 7", "manufacturer": "Boeing", "model": "737 MAX 7"},
    "B38M": {"name": "Boeing 737 MAX 8", "manufacturer": "Boeing", "model": "737 MAX 8"},
    "B39M": {"name": "Boeing 737 MAX 9", "manufacturer": "Boeing", "model": "737 MAX 9"},
    "B3XM": {"name": "Boeing 737 MAX 10", "manufacturer": "Boeing", "model": "737 MAX 10"},
    "B744": {"name": "Boeing 747-400", "manufacturer": "Boeing", "model": "747-400"},
    "B748": {"name": "Boeing 747-8", "manufacturer": "Boeing", "model": "747-8"},
    "B752": {"name": "Boeing 757-200", "manufacturer": "Boeing", "model": "757-200"},
    "B753": {"name": "Boeing 757-300", "manufacturer": "Boeing", "model": "757-300"},
    "B762": {"name": "Boeing 767-200", "manufacturer": "Boeing", "model": "767-200"},
    "B763": {"name": "Boeing 767-300", "manufacturer": "Boeing", "model": "767-300"},
    "B764": {"name": "Boeing 767-400", "manufacturer": "Boeing", "model": "767-400"},
    "B772": {"name": "Boeing 777-200", "manufacturer": "Boeing", "model": "777-200"},
    "B77L": {"name": "Boeing 777-200LR", "manufacturer": "Boeing", "model": "777-200LR"},
    "B773": {"name": "Boeing 777-300", "manufacturer": "Boeing", "model": "777-300"},
    "B77W": {"name": "Boeing 777-300ER", "manufacturer": "Boeing", "model": "777-300ER"},
    "B778": {"name": "Boeing 777-8", "manufacturer": "Boeing", "model": "777-8"},
    "B779": {"name": "Boeing 777-9", "manufacturer": "Boeing", "model": "777-9"},
    "B788": {"name": "Boeing 787-8 Dreamliner", "manufacturer": "Boeing", "model": "787-8"},
    "B789": {"name": "Boeing 787-9 Dreamliner", "manufacturer": "Boeing", "model": "787-9"},
    "B78X": {"name": "Boeing 787-10 Dreamliner", "manufacturer": "Boeing", "model": "787-10"},
    "B712": {"name": "Boeing 717-200", "manufacturer": "Boeing", "model": "717-200"},
    # Airbus Commercial
    "A318": {"name": "Airbus A318", "manufacturer": "Airbus", "model": "A318"},
    "A319": {"name": "Airbus A319", "manufacturer": "Airbus", "model": "A319"},
    "A320": {"name": "Airbus A320", "manufacturer": "Airbus", "model": "A320"},
    "A321": {"name": "Airbus A321", "manufacturer": "Airbus", "model": "A321"},
    "A19N": {"name": "Airbus A319neo", "manufacturer": "Airbus", "model": "A319neo"},
    "A20N": {"name": "Airbus A320neo", "manufacturer": "Airbus", "model": "A320neo"},
    "A21N": {"name": "Airbus A321neo", "manufacturer": "Airbus", "model": "A321neo"},
    "A21X": {"name": "Airbus A321XLR", "manufacturer": "Airbus", "model": "A321XLR"},
    "A332": {"name": "Airbus A330-200", "manufacturer": "Airbus", "model": "A330-200"},
    "A333": {"name": "Airbus A330-300", "manufacturer": "Airbus", "model": "A330-300"},
    "A338": {"name": "Airbus A330-800neo", "manufacturer": "Airbus", "model": "A330-800neo"},
    "A339": {"name": "Airbus A330-900neo", "manufacturer": "Airbus", "model": "A330-900neo"},
    "A342": {"name": "Airbus A340-200", "manufacturer": "Airbus", "model": "A340-200"},
    "A343": {"name": "Airbus A340-300", "manufacturer": "Airbus", "model": "A340-300"},
    "A345": {"name": "Airbus A340-500", "manufacturer": "Airbus", "model": "A340-500"},
    "A346": {"name": "Airbus A340-600", "manufacturer": "Airbus", "model": "A340-600"},
    "A359": {"name": "Airbus A350-900", "manufacturer": "Airbus", "model": "A350-900"},
    "A35K": {"name": "Airbus A350-1000", "manufacturer": "Airbus", "model": "A350-1000"},
    "A388": {"name": "Airbus A380-800", "manufacturer": "Airbus", "model": "A380-800"},
    "BCS1": {"name": "Airbus A220-100", "manufacturer": "Airbus", "model": "A220-100"},
    "BCS3": {"name": "Airbus A220-300", "manufacturer": "Airbus", "model": "A220-300"},
    "A221": {"name": "Airbus A220-100", "manufacturer": "Airbus", "model": "A220-100"},
    "A223": {"name": "Airbus A220-300", "manufacturer": "Airbus", "model": "A220-300"},
    # Embraer
    "E170": {"name": "Embraer E170", "manufacturer": "Embraer", "model": "E170"},
    "E75L": {"name": "Embraer E175 (Enhanced Wingtips)", "manufacturer": "Embraer", "model": "E175"},
    "E75S": {"name": "Embraer E175 (Standard)", "manufacturer": "Embraer", "model": "E175"},
    "E175": {"name": "Embraer E175", "manufacturer": "Embraer", "model": "E175"},
    "E190": {"name": "Embraer E190", "manufacturer": "Embraer", "model": "E190"},
    "E195": {"name": "Embraer E195", "manufacturer": "Embraer", "model": "E195"},
    "E290": {"name": "Embraer E190-E2", "manufacturer": "Embraer", "model": "E190-E2"},
    "E295": {"name": "Embraer E195-E2", "manufacturer": "Embraer", "model": "E195-E2"},
    "E135": {"name": "Embraer ERJ-135", "manufacturer": "Embraer", "model": "ERJ-135"},
    "E145": {"name": "Embraer ERJ-145", "manufacturer": "Embraer", "model": "ERJ-145"},
    # Bombardier / Regional
    "CRJ1": {"name": "Bombardier CRJ-100", "manufacturer": "Bombardier", "model": "CRJ-100"},
    "CRJ2": {"name": "Bombardier CRJ-200", "manufacturer": "Bombardier", "model": "CRJ-200"},
    "CRJ7": {"name": "Bombardier CRJ-700", "manufacturer": "Bombardier", "model": "CRJ-700"},
    "CRJ9": {"name": "Bombardier CRJ-900", "manufacturer": "Bombardier", "model": "CRJ-900"},
    "CRJX": {"name": "Bombardier CRJ-1000", "manufacturer": "Bombardier", "model": "CRJ-1000"},
    # De Havilland Canada / ATR Turboprops
    "DH8A": {"name": "De Havilland Dash 8-100", "manufacturer": "De Havilland Canada", "model": "Dash 8-100"},
    "DH8B": {"name": "De Havilland Dash 8-200", "manufacturer": "De Havilland Canada", "model": "Dash 8-200"},
    "DH8C": {"name": "De Havilland Dash 8-300", "manufacturer": "De Havilland Canada", "model": "Dash 8-300"},
    "DH8D": {"name": "De Havilland Dash 8-400", "manufacturer": "De Havilland Canada", "model": "Dash 8-400"},
    "DHC6": {"name": "De Havilland DHC-6 Twin Otter", "manufacturer": "De Havilland Canada", "model": "DHC-6"},
    "AT43": {"name": "ATR 42-300", "manufacturer": "ATR", "model": "42-300"},
    "AT45": {"name": "ATR 42-500", "manufacturer": "ATR", "model": "42-500"},
    "AT46": {"name": "ATR 42-600", "manufacturer": "ATR", "model": "42-600"},
    "AT72": {"name": "ATR 72-200", "manufacturer": "ATR", "model": "72-200"},
    "AT73": {"name": "ATR 72-210", "manufacturer": "ATR", "model": "72-210"},
    "AT75": {"name": "ATR 72-500", "manufacturer": "ATR", "model": "72-500"},
    "AT76": {"name": "ATR 72-600", "manufacturer": "ATR", "model": "72-600"},
    "SF34": {"name": "Saab 340", "manufacturer": "Saab", "model": "340"},
    "SB20": {"name": "Saab 2000", "manufacturer": "Saab", "model": "2000"},
    # General Aviation
    "C150": {"name": "Cessna 150", "manufacturer": "Cessna", "model": "150"},
    "C152": {"name": "Cessna 152", "manufacturer": "Cessna", "model": "152"},
    "C172": {"name": "Cessna 172 Skyhawk", "manufacturer": "Cessna", "model": "172 Skyhawk"},
    "C182": {"name": "Cessna 182 Skylane", "manufacturer": "Cessna", "model": "182 Skylane"},
    "C206": {"name": "Cessna 206 Stationair", "manufacturer": "Cessna", "model": "206 Stationair"},
    "C208": {"name": "Cessna 208 Caravan", "manufacturer": "Cessna", "model": "208 Caravan"},
    "C210": {"name": "Cessna 210 Centurion", "manufacturer": "Cessna", "model": "210 Centurion"},
    "PA28": {"name": "Piper PA-28 Cherokee", "manufacturer": "Piper", "model": "PA-28 Cherokee"},
    "PA32": {"name": "Piper PA-32 Cherokee Six / Saratoga", "manufacturer": "Piper", "model": "PA-32"},
    "PA34": {"name": "Piper PA-34 Seneca", "manufacturer": "Piper", "model": "PA-34 Seneca"},
    "PA44": {"name": "Piper PA-44 Seminole", "manufacturer": "Piper", "model": "PA-44 Seminole"},
    "PA46": {"name": "Piper PA-46 Malibu / Matrix", "manufacturer": "Piper", "model": "PA-46"},
    "SR20": {"name": "Cirrus SR20", "manufacturer": "Cirrus", "model": "SR20"},
    "SR22": {"name": "Cirrus SR22", "manufacturer": "Cirrus", "model": "SR22"},
    "SF50": {"name": "Cirrus Vision Jet", "manufacturer": "Cirrus", "model": "Vision Jet"},
    "BE33": {"name": "Beechcraft Bonanza 33", "manufacturer": "Beechcraft", "model": "Bonanza 33"},
    "BE35": {"name": "Beechcraft Bonanza 35", "manufacturer": "Beechcraft", "model": "Bonanza 35"},
    "BE36": {"name": "Beechcraft Bonanza 36", "manufacturer": "Beechcraft", "model": "Bonanza 36"},
    "BE55": {"name": "Beechcraft Baron 55", "manufacturer": "Beechcraft", "model": "Baron 55"},
    "BE58": {"name": "Beechcraft Baron 58", "manufacturer": "Beechcraft", "model": "Baron 58"},
    "BE9L": {"name": "Beechcraft King Air 90", "manufacturer": "Beechcraft", "model": "King Air 90"},
    "BE20": {"name": "Beechcraft Super King Air 200", "manufacturer": "Beechcraft", "model": "King Air 200"},
    "B350": {"name": "Beechcraft Super King Air 350", "manufacturer": "Beechcraft", "model": "King Air 350"},
    "BE40": {"name": "Beechjet 400", "manufacturer": "Beechcraft", "model": "Beechjet 400"},
    "PC12": {"name": "Pilatus PC-12", "manufacturer": "Pilatus", "model": "PC-12"},
    "PC24": {"name": "Pilatus PC-24", "manufacturer": "Pilatus", "model": "PC-24"},
    "TBM7": {"name": "Daher TBM 700", "manufacturer": "Daher", "model": "TBM 700"},
    "TBM8": {"name": "Daher TBM 850", "manufacturer": "Daher", "model": "TBM 850"},
    "TBM9": {"name": "Daher TBM 900 / 930 / 960", "manufacturer": "Daher", "model": "TBM 900"},
    "DA20": {"name": "Diamond DA20 Katana", "manufacturer": "Diamond", "model": "DA20 Katana"},
    "DA40": {"name": "Diamond DA40 Diamond Star", "manufacturer": "Diamond", "model": "DA40"},
    "DA42": {"name": "Diamond DA42 Twin Star", "manufacturer": "Diamond", "model": "DA42"},
    "DA62": {"name": "Diamond DA62", "manufacturer": "Diamond", "model": "DA62"},
    # Business Jets
    "C510": {"name": "Cessna Citation Mustang", "manufacturer": "Cessna", "model": "Citation Mustang"},
    "C525": {"name": "Cessna CitationJet / CJ1", "manufacturer": "Cessna", "model": "Citation CJ1"},
    "C25A": {"name": "Cessna Citation CJ2", "manufacturer": "Cessna", "model": "Citation CJ2"},
    "C25B": {"name": "Cessna Citation CJ3", "manufacturer": "Cessna", "model": "Citation CJ3"},
    "C25C": {"name": "Cessna Citation CJ4", "manufacturer": "Cessna", "model": "Citation CJ4"},
    "C550": {"name": "Cessna Citation II / Bravo", "manufacturer": "Cessna", "model": "Citation II"},
    "C560": {"name": "Cessna Citation V / Ultra / Encore", "manufacturer": "Cessna", "model": "Citation V"},
    "C56X": {"name": "Cessna Citation Excel / XLS", "manufacturer": "Cessna", "model": "Citation Excel"},
    "C680": {"name": "Cessna Citation Sovereign", "manufacturer": "Cessna", "model": "Citation Sovereign"},
    "C68A": {"name": "Cessna Citation Latitude", "manufacturer": "Cessna", "model": "Citation Latitude"},
    "C700": {"name": "Cessna Citation Longitude", "manufacturer": "Cessna", "model": "Citation Longitude"},
    "C750": {"name": "Cessna Citation X", "manufacturer": "Cessna", "model": "Citation X"},
    "CL30": {"name": "Bombardier Challenger 300", "manufacturer": "Bombardier", "model": "Challenger 300"},
    "CL35": {"name": "Bombardier Challenger 350", "manufacturer": "Bombardier", "model": "Challenger 350"},
    "CL60": {"name": "Bombardier Challenger 600 / 604 / 650", "manufacturer": "Bombardier", "model": "Challenger 600"},
    "GLEX": {"name": "Bombardier Global Express / 6000", "manufacturer": "Bombardier", "model": "Global Express"},
    "GL5T": {"name": "Bombardier Global 5000 / 5500", "manufacturer": "Bombardier", "model": "Global 5000"},
    "GL7T": {"name": "Bombardier Global 7500", "manufacturer": "Bombardier", "model": "Global 7500"},
    "GLF4": {"name": "Gulfstream IV / G450", "manufacturer": "Gulfstream", "model": "G450"},
    "GLF5": {"name": "Gulfstream V / G550", "manufacturer": "Gulfstream", "model": "G550"},
    "GLF6": {"name": "Gulfstream G650 / G700", "manufacturer": "Gulfstream", "model": "G650"},
    "G280": {"name": "Gulfstream G280", "manufacturer": "Gulfstream", "model": "G280"},
    "FA50": {"name": "Dassault Falcon 50", "manufacturer": "Dassault", "model": "Falcon 50"},
    "FA7X": {"name": "Dassault Falcon 7X", "manufacturer": "Dassault", "model": "Falcon 7X"},
    "FA8X": {"name": "Dassault Falcon 8X", "manufacturer": "Dassault", "model": "Falcon 8X"},
    "F900": {"name": "Dassault Falcon 900", "manufacturer": "Dassault", "model": "Falcon 900"},
    "F2TH": {"name": "Dassault Falcon 2000", "manufacturer": "Dassault", "model": "Falcon 2000"},
    "LJ35": {"name": "Learjet 35", "manufacturer": "Learjet", "model": "35"},
    "LJ45": {"name": "Learjet 45", "manufacturer": "Learjet", "model": "45"},
    "LJ60": {"name": "Learjet 60", "manufacturer": "Learjet", "model": "60"},
    "LJ75": {"name": "Learjet 75", "manufacturer": "Learjet", "model": "75"},
    "E50P": {"name": "Embraer Phenom 100", "manufacturer": "Embraer", "model": "Phenom 100"},
    "E55P": {"name": "Embraer Phenom 300", "manufacturer": "Embraer", "model": "Phenom 300"},
    "E545": {"name": "Embraer Legacy 450 / Praetor 500", "manufacturer": "Embraer", "model": "Legacy 450"},
    "E550": {"name": "Embraer Legacy 500 / Praetor 600", "manufacturer": "Embraer", "model": "Legacy 500"},
    "HA420": {"name": "HondaJet HA-420", "manufacturer": "Honda", "model": "HA-420"},
    # Helicopters
    "R22": {"name": "Robinson R22", "manufacturer": "Robinson", "model": "R22"},
    "R44": {"name": "Robinson R44", "manufacturer": "Robinson", "model": "R44"},
    "R66": {"name": "Robinson R66", "manufacturer": "Robinson", "model": "R66"},
    "B06": {"name": "Bell 206 JetRanger", "manufacturer": "Bell", "model": "206 JetRanger"},
    "B407": {"name": "Bell 407", "manufacturer": "Bell", "model": "407"},
    "B412": {"name": "Bell 412", "manufacturer": "Bell", "model": "412"},
    "B429": {"name": "Bell 429 GlobalRanger", "manufacturer": "Bell", "model": "429"},
    "EC20": {"name": "Eurocopter EC120 Colibri", "manufacturer": "Eurocopter", "model": "EC120"},
    "EC30": {"name": "Eurocopter EC130", "manufacturer": "Eurocopter", "model": "EC130"},
    "AS50": {"name": "Eurocopter AS350 Écureuil", "manufacturer": "Eurocopter", "model": "AS350"},
    "EC35": {"name": "Airbus Helicopters H135 / EC135", "manufacturer": "Airbus Helicopters", "model": "H135"},
    "H135": {"name": "Airbus Helicopters H135", "manufacturer": "Airbus Helicopters", "model": "H135"},
    "EC45": {"name": "Airbus Helicopters H145 / EC145", "manufacturer": "Airbus Helicopters", "model": "H145"},
    "H145": {"name": "Airbus Helicopters H145", "manufacturer": "Airbus Helicopters", "model": "H145"},
    "AS65": {"name": "Eurocopter AS365 Dauphin", "manufacturer": "Eurocopter", "model": "AS365"},
    "H155": {"name": "Airbus Helicopters H155", "manufacturer": "Airbus Helicopters", "model": "H155"},
    "H160": {"name": "Airbus Helicopters H160", "manufacturer": "Airbus Helicopters", "model": "H160"},
    "H225": {"name": "Airbus Helicopters H225 Super Puma", "manufacturer": "Airbus Helicopters", "model": "H225"},
    "AS32": {"name": "Eurocopter AS332 Super Puma", "manufacturer": "Eurocopter", "model": "AS332"},
    "S76": {"name": "Sikorsky S-76", "manufacturer": "Sikorsky", "model": "S-76"},
    "S92": {"name": "Sikorsky S-92", "manufacturer": "Sikorsky", "model": "S-92"},
    "UH60": {"name": "Sikorsky UH-60 Black Hawk", "manufacturer": "Sikorsky", "model": "UH-60"},
    "CH47": {"name": "Boeing CH-47 Chinook", "manufacturer": "Boeing", "model": "CH-47"},
    "A139": {"name": "AgustaWestland AW139", "manufacturer": "AgustaWestland", "model": "AW139"},
    "AW139": {"name": "AgustaWestland AW139", "manufacturer": "AgustaWestland", "model": "AW139"},
    "A109": {"name": "AgustaWestland AW109", "manufacturer": "AgustaWestland", "model": "AW109"},
    "AW109": {"name": "AgustaWestland AW109", "manufacturer": "AgustaWestland", "model": "AW109"},
    "AW169": {"name": "AgustaWestland AW169", "manufacturer": "AgustaWestland", "model": "AW169"},
    "AW189": {"name": "AgustaWestland AW189", "manufacturer": "AgustaWestland", "model": "AW189"},
    "MD52": {"name": "MD Helicopters MD 500", "manufacturer": "MD Helicopters", "model": "MD 500"},
}


def lookup_aircraft(type_code: str | None) -> dict[str, str | None]:
    """Look up aircraft details from an ICAO aircraft type designator code.

    Returns dict with keys:
    - 'name': Full descriptive name (e.g. "Boeing 737-800")
    - 'manufacturer': Manufacturer name (e.g. "Boeing")
    - 'model': Model name (e.g. "737-800")
    """
    if not type_code:
        return {"name": None, "manufacturer": None, "model": None}

    cleaned = type_code.strip().upper()
    info = AIRCRAFT_BY_ICAO.get(cleaned)
    if info:
        return {
            "name": info["name"],
            "manufacturer": info["manufacturer"],
            "model": info["model"],
        }

    return {"name": None, "manufacturer": None, "model": None}
